# Seguros

Avaliação de seguros. Queremos prever se haverá acidente, assim, a variável dependente (target) será a coluna $\text{accident}$.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from yellowbrick.classifier import ConfusionMatrix

In [2]:
from pathlib import Path
__THIS_PATH__ = Path().resolve()
__ROOT_PATH__ = __THIS_PATH__.parents[1]
__DATA_PATH__ = __ROOT_PATH__ / "data"

In [3]:
base_raw = pd.read_csv(__ROOT_PATH__/ 'data/insurance.csv')
print(base_raw.shape)
base_raw.head()

(20000, 28)

,Unnamed: 0,GoodStudent,Age,SocioEcon,RiskAversion,VehicleYear,ThisCarDam,RuggedAuto,Accident,MakeModel,...,HomeBase,AntiTheft,PropCost,OtherCarCost,OtherCar,MedCost,Cushioning,Airbag,ILiCost,DrivHist
0,1,False,Adult,Prole,Adventurous,Older,Moderate,EggShell,Mild,Economy,...,City,False,TenThou,Thousand,True,Thousand,Poor,False,Thousand,Many
1,2,False,Senior,Prole,Cautious,Current,NaN,Football,NaN,Economy,...,City,True,Thousand,Thousand,True,Thousand,Good,True,Thousand,Zero
2,3,False,Senior,UpperMiddle,Psychopath,Current,NaN,Football,NaN,FamilySedan,...,City,False,Thousand,Thousand,False,Thousand,Good,True,Thousand,One
3,4,False,Adolescent,Middle,Normal,Older,NaN,EggShell,NaN,Economy,...,Suburb,False,Thousand,Thousand,True,Thousand,Fair,False,Thousand,Zero
4,5,False,Adolescent,Prole,Normal,Older,Moderate,Football,Moderate,Economy,...,City,False,TenThou,Thousand,False,Thousand,Fair,False,Thousand,Many

In [4]:
# Removendo a coluna de nomes - Variável que não interessa na REgresssao.
base = base_raw.drop(columns = ['Unnamed: 0'])
print(base.shape)
base.head()

(20000, 27)

,GoodStudent,Age,SocioEcon,RiskAversion,VehicleYear,ThisCarDam,RuggedAuto,Accident,MakeModel,DrivQuality,...,HomeBase,AntiTheft,PropCost,OtherCarCost,OtherCar,MedCost,Cushioning,Airbag,ILiCost,DrivHist
0,False,Adult,Prole,Adventurous,Older,Moderate,EggShell,Mild,Economy,Poor,...,City,False,TenThou,Thousand,True,Thousand,Poor,False,Thousand,Many
1,False,Senior,Prole,Cautious,Current,NaN,Football,NaN,Economy,Normal,...,City,True,Thousand,Thousand,True,Thousand,Good,True,Thousand,Zero
2,False,Senior,UpperMiddle,Psychopath,Current,NaN,Football,NaN,FamilySedan,Excellent,...,City,False,Thousand,Thousand,False,Thousand,Good,True,Thousand,One
3,False,Adolescent,Middle,Normal,Older,NaN,EggShell,NaN,Economy,Normal,...,Suburb,False,Thousand,Thousand,True,Thousand,Fair,False,Thousand,Zero
4,False,Adolescent,Prole,Normal,Older,Moderate,Football,Moderate,Economy,Poor,...,City,False,TenThou,Thousand,False,Thousand,Fair,False,Thousand,Many

y minúsculo e X maíusculo.

In [5]:
# variavel dependente, quero todas as linhas da coluna índice 7
y = base.iloc[:,7].values

# variáveis independentes, quero todas as linhas das outras colunas, ignorando a setima.
X = base.iloc[:,[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]].values

# by FK
X0 = base.iloc[:, np.r_[0:7,8:27]].values
assert X0.all() == X.all()

In [6]:
set(y)

{'Mild', 'Moderate', 'Severe', nan}

In [7]:
X[1:3]

array([[False, 'Senior', 'Prole', 'Cautious', 'Current', nan, 'Football',
        'Economy', 'Normal', 'TwentyThou', False, 'Normal', True,
        'Thousand', False, 'TenThou', 'City', True, 'Thousand',
        'Thousand', True, 'Thousand', 'Good', True, 'Thousand', 'Zero'],
       [False, 'Senior', 'UpperMiddle', 'Psychopath', 'Current', nan,
        'Football', 'FamilySedan', 'Excellent', 'Domino', True, 'Normal',
        False, 'Thousand', False, 'TwentyThou', 'City', False,
        'Thousand', 'Thousand', False, 'Thousand', 'Good', True,
        'Thousand', 'One']], dtype=object)